import { ServiceProvider } from "@/app/data/serviceContext"
import type { Metadata } from "next"
import { Geist, Geist_Mono, Staatliches } from "next/font/google"
import "@/app/globals.css"
import Nav from "@/components/nav"
import Footer from "@/components/footer"



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

const staatliches = Staatliches({
  // 2. Configure the font
  weight: "400", // Staatliches usually only has one weight
  variable: "--font-staatliches",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${staatliches.variable} antialiased bg-zinc-950 text-zinc-100 overflow-x-hidden`}
      >
        <Nav />
        <main className="">
          <ServiceProvider>{children}</ServiceProvider>
        </main>
        <Footer />
      </body>
    </html>
  )
}
